<<<<<<< Updated upstream
email: test@gmail.com
password: testpassword
=======
email: shwetamath127@gmail.com
password: login@1234567890
>>>>>>> Stashed changes

disableAntiLock: False

remote: False

experienceLevel:
 internship: True
 entry: False
 associate: True
 mid-senior level: True
 director: False
 executive: False
 
jobTypes:
 full-time: True
 contract: True
 part-time: True
 temporary: True
 internship: True
 other: True
 volunteer: True
 
date:
 all time: True
 month: False
 week: True
 24 hours: False
 
positions:
 - Associate

locations:
 - Bangalore Urban, Karnataka, India

distance: 0

outputFileDirectory: C:\Users\DELL\Desktop

companyBlacklist:
 #- company
 #- company2

titleBlacklist:
 #- word1
 #- word2

uploads:
 resume: C:\Users\DELL\Desktop\Resume.pdf
 # Cover letter is optional
 #coverLetter: C:\Users\myDirectory\CoverLettter.pdf


# ------------ QA section -------------------

# ------------ Additional parameters: checkboxes ---------------
checkboxes:
 # Do you have a valid driver's license? (yes/no checkbox)
 driversLicence: False
 # Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)? (yes/no checkbox)
 # This is relative to the location and your citizenship applying above, and same with legallyAuthorized.
 requireVisa: False
 # Are you legally authorized to work in COUNTRY? (yes/no checkbox)
 legallyAuthorized: True
 # We must fill this position urgently. Can you start immediately? (yes/no checkbox)
 urgentFill: True
 # Are you comfortable commuting to this job's location? (yes/no checkbox)
 commute: True
 # Have you completed the following level of education: DEGREE TYPE? (yes/no checkbox)
 degreeCompleted:
  High School Diploma: True
  Bachelor's Degree: True

 # Are you willing to undergo a background check, in accordance with local law/regulations?
 backgroundCheck: True

# ------------ Additional parameters: univeristyGpa ---------------
universityGpa: 3.0

# ------------ Additional parameters: languages ---------------
languages:
 english: Native or bilingual # None, Conversational, Professional, Native or bilingual


# ------------ Additional parameters: years of INDUSTRY experience ---------------
# How many years of TECHNOLOGY experience do you currently have? (whole numbers only)
industry:
 # normal ones
 Accounting/Auditing: 0
 Administrative : 2
 Advertising : 2
 Analyst : 0
 Art/Creative: 0
 Business Development: 1
 Consulting: 0
 Customer Service: 3
 Distribution Design: 0
 Education: 0
 Engineering: 0
 Finance: 0
 General Business: 0
 Health Care Provider: 0
 Human Resources: 0
 Information Technology: 1
 Legal: 0
 Management: 0
 Manufacturing: 0
 Marketing: 2
 Public Relations: 0
 Purchasing: 0
 Product Management: 0
 Project Management: 0
 Production: 0
 Quality Assurance: 0
 Research: 0
 Sales: 0
 Science: 0
 Strategy/Planning: 0
 Supply Chain: 0
 Training: 0
 Writing/Editing: 0
 # end normal ones
 # put your custom ones here
 #C++: 0
 #Python: 1
 # default to put for any skill that you did not list
 default: 0
 # end custom ones


# ------------ Additional parameters: years of technology experience ---------------
# How many years of work experience do you have using TECHNOLOGY? (whole numbers only)
technology:
 #python: 0
 #selenium: 0
 # default to put for any skill that you did not list
 default: 0
# ------------ Additional parameters: personal info ---------------
personalInfo:
 First Name: Shweta
 Last Name: Mathapati
 Phone Country Code: India (+91) # See linkedin for your country code, must be exact
<<<<<<< Updated upstream
 Mobile Phone Number: 00000000000
 Street address: 0 Ft road, Silver Layout
 City: Bangalore # Include the state/province as well!
 State: Karnataka
 Zip: 000000
=======
 Mobile Phone Number: 6360244504
 Street address: 100 Ft road, Silver Spring Layout
 City: Kundalahalli,Bangalore # Include the state/province as well!
 State: Karnataka
 Zip: 560037
>>>>>>> Stashed changes
 Linkedin: https://www.linkedin.com/in/mathshwe/
 Website: https://www.dreamworksgoal.com # github/website is interchangable here

# ------------ Additional parameters: USA employment crap ---------------
eeo:
 gender: Female
 race: None
 vetran: None
 disability: None
<<<<<<< Updated upstream
 citizenship: Indian
=======
 citizenship: Indian
>>>>>>> Stashed changes
